# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-fpm-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo
    environment:

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # build assets
      - run:
          name: Build assets
          command: yarn encore dev

      # add environment variables
      - run: " export PAGSEGURO_ENV=$PAGSEGURO_ENV  && \
               export PAGSEGURO_EMAIL=$PAGSEGURO_EMAIL && \
               export PAGSEGURO_TOKEN_SANDBOX=$PAGSEGURO_TOKEN_SANDBOX && \
               export PAGSEGURO_APP_ID_SANDBOX=$PAGSEGURO_APP_ID_SANDBOX && \
               export PAGSEGURO_APP_KEY_SANDBOX=$PAGSEGURO_APP_KEY_SANDBOX && \
               export PAGSEGURO_CHARSET=$PAGSEGURO_CHARSET && \
               export PAGSEGURO_LOG_ACTIVE=$PAGSEGURO_LOG_ACTIVE"
      # run tests!
      - run: bin/phpunit
