index:
    path: /
    controller: App\Controller\DefaultController::index
pagseguro_session:
    path: /pagseguro/session
    controller: App\Controller\PagSeguroController::getSessionId
pagseguro_credit_card_payment:
    path: /pagseguro/creditCardPayment
    controller: App\Controller\PagSeguroController::postCreditCardPayment
